allowExternalScriptLabels=yes
autoBackupFileOnWatch=yes
trayIcon=yes
showSafeModeWarnings=yes
surtrPath=C:\\Surtr\\surtr
webuiSurtrWaitTimeout=120
useWebuiDefaultSurtrTheme=yes
useSurtrTheme=no
surtrUiOutput=shell
keepOutputShellOpen=no
showShellWhenRunningTask=yes